name = "paunix-guard"
compatibility_date = "2026-05-17"
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "PAUNIX_RELEASES"
bucket_name = "paunix-guard-releases"
preview_bucket_name = "paunix-guard-releases-preview"

[vars]
PUBLIC_SITE_URL = "https://paunixguard.pages.dev"
PUBLIC_DOWNLOAD_FALLBACK_URL = "https://github.com/paundrapf/Paunix-Guard/releases/download/v0.1.1/PaunixGuard-win-Setup.exe"
